Repository technance-foundation/github-actions, pull requests merged in 2025-09, with the labels that each got.

#5 Add `load-env` action
  .github/actions/load-env/README.md
  .github/actions/load-env/action.yml
  README.md
Labels: Type - Feature

#6 Simplify path of the actions
  .github/actions/check
  .github/actions/load-env
  .github/actions/publish-any-commit
  .github/actions/release
  .github/actions/telegram-notifications
  CODEOWNERS
  README.md
  check/README.md
  check/action.yml
  load-env/README.md
  load-env/action.yml
  publish-any-commit/README.md
  publish-any-commit/action.yml
  release/README.md
  release/action.yml
  telegram-notifications/README.md
  telegram-notifications/action.yml
Labels: Type - Refactor

#7 Add missing `NPM_TOKEN` env var to authentication step
  publish-any-commit/README.md
  publish-any-commit/action.yml
  release/README.md
  release/action.yml
Labels: Type - Fix

#9 Separate changesets base branch from PR target branch
  release/README.md
  release/action.yml
Labels: Type - Fix

#13 Add support for readonly pnpm cache in the `setup`
  setup/README.md
  setup/action.yml
Labels: Type - Feature

#12 Drop the `check` action
  .github/actions/check
  README.md
  check/README.md
  check/action.yml
Labels: Type - Refactor
